### ISSUE TITLE
webpack源码系列文章中的实例代码在哪里呀

### ISSUE THREAD

**Issue by Giancarlo-Ma** [wbccb/wbccb#1]
https://segmentfault.com/a/1190000043845501#item-4-1
![image](https://github.com/wbccb/wbccb/assets/65126107/d671f9b6-e487-4252-94d4-3dcb548efb3a)
就是这个图对应的代码

**Comment by wbccb** [comment]
记不清楚了，应该是这个 

https://github.com/wbccb/Frontend-Articles/tree/main/webpack-debugger/js-test-require-splitchunkplugin

可以去 https://github.com/wbccb/Frontend-Articles/tree/main/webpack-debugger 这个文件夹找找 @Giancarlo-Ma
